--- 
title: "Data Science für die Humangeographie: Ein pragmatischer Einstieg mit R"
subtitle: Projektseminar Konzeption quantitativer Forschung
author:
  - name: Till Straube
    url: https://user.uni-frankfurt.de/~tstraube
    email: straube@geo.uni-frankfurt.de
    affiliation: |
      | Institut für Humangeographie
      | Goethe-Universität Frankfurt
date: "Winter- und Sommersemester 2020/21"
site: bookdown::bookdown_site
documentclass: article
bibliography: ["datascience.bib"]
link-citations: yes
lang: de
description: "Projektseminar"
---

```{r include=F}
knitr::opts_chunk$set(cache = T,
                      warning = F,
                      message = F,
                      collapse = T,
                      dev = 'png')

solutions <- knitr::opts_knit$get("rmarkdown.pandoc.to") == "html"
```

# Terminüberblick {-}

*Alle Sitzungen finden von 13 bis 16h c.t. statt*

Datum                 | Sitzung | Inhalt
--------------------: | ------: | :-----------------------------------
2. November 2020      | 1       | [Vorbesprechung](#vorbesprechung)
9. November 2020      | 2       | [Erste Schritte](#erste-schritte)
16. November 2020     | 3       | [Text: Anderson 2008](#text-anderson-2008)
23. November 2020     | 4       | [Datenstrukturen](#datenstrukturen)
30. November 2020     | 5       | [Visualisierungen](#visualisierungen)
7. Dezember 2020      | 6       | [Text: Shelton et al. 2014](#text-shelton-et-al.-2014)
14. Dezember 2020     | 7       | [Geodaten](#geodaten)
11. Januar 2021       | 8       | [Choroplethen](#choroplethen)
18. Januar 2021       | 9       | [Text: Chandra 2014](#text-chandra-2014)
25. Januar 2021       | 10      | [HTML-Tabellen](#html-tabellen)
1. Februar 2021       | 11      | [Web scraping](#web-scraping)
8. Februar 2021       | 12      | [Text: Straube 2021](#text-straube-2021)
15. Februar 2021      | 13      | [Präsentationen]
*31. März 2021*       |         | *Abgabe Exposé*
12. April 2021        | 14      | [APIs]
19. April 2021        | 15      | [Serialisierung]
26. April 2021        | 16      | [Text: Breuer 2005]
3. Mai 2021           | 17      | [String manipulation]
10. Mai 2021          | 18      | [Join und group]
17. Mai 2021          | 19      | [Rmarkdown und Kollaboration]
*24. Mai 2021*        |         | *Entfällt (Pfingstmontag)*
31. Mai 2021          | 20      | [Text: Bowker und Star 1999]
7. Juni 2021          | 21      | [Interaktive Visualisierungen]
14. Juni 2021         | 22      | [Clusteranalyse]
21. Juni 2021         | 23      | [Varianzanalyse]
28. Juni 2021         | 24      | [Text: Beer 2017]
5. Juli 2021          | 25      | [Präsentationen]
12. Juli 2021         | 26      | [Präsentationen]
